# Configure ${} variables in .env file same as .env.example
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
  application:
    name: URLShortener

server:
  port: 8080

url:
  shortener:
    base-url: ${URL_SHORTENER_BASE_URL}
